### ISSUE TITLE
SOP Encryption using public key with no expiry fails

### ISSUE THREAD

**Issue by brownmb** [pgpainless/sop-java#27]
Hi.

Using SOP 1.66.

Encryption using 3rd party public key which has no expiry fails with exception.

```
Exception in thread "main" org.pgpainless.exception.KeyException$UnacceptableSelfSignatureException: Key 37518BFC71C9B490C9980F489E459E50958DA76C does not have a valid/acceptable signature to derive an expiration date from.
	at org.pgpainless.encryption_signing.EncryptionOptions.addAsRecipient(EncryptionOptions.java:298)
	at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:265)
	at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:253)
	at com.hw.midoffice.tools.pgp.PgpTools.encrypt(PgpTools.java:244)
```

Used desktop tools to encrypt with the same public key without issue so wondering if this is a bug?

**Comment by vanitasvitae** [comment]
For the future:
You appear to be using PGPainless without using the SOP interface, so please use [this issue tracker](https://github.com/pgpainless/pgpainless/issues) instead.
Also, please use the issue template instead.

I suspect that the public key you are trying to encrypt a message to does use SHA-1 as the signature algorithm for self-signatures.
PGPainless rejects those signatures if they were made after a certain cutoff-date, as SHA-1 is considered inappropriate due to safety concerns.

To fix your problem you have two options:
* if you can reach the key owner, get them to fix their key by them issuing new self-signatures using a safe hash algorithm
* otherwise, you can [teach PGPainless](https://github.com/pgpainless/pgpainless/blob/master/pgpainless-core/src/test/java/org/pgpainless/example/ManagePolicy.java#L92-L99) to accept signatures with SHA-1, although the first option is preferable in the long run.


Also read: https://pgpainless.readthedocs.io/en/latest/quickstart.html#weak-keys-and-broken-algorithms

**Comment by brownmb** [comment]
Many thanks Paul.    Ive actually got two versions...sop and core.  They both do the same thing.   My exception will be from the core test.  Sorry for the confusion and I will use the Issue Tracker next time.

The 3rd party im working with are unlikely to change the keys anytime soon.  Its only their test environment and the real production keys will be created by myself.  Ill take a look at teaching PGPainless to allow the older algo's,

Thanks again!

**Comment by brownmb** [comment]
The profile configuration worked!

Thank you very much..  Really apprecicate you taking the time to answer this query.
